<div className="mt-6 relative">
    <a class=" block max-w-md p-px mx-auto overflow-hidden transition duration-10000 transform bg-white border border-gray-400 rounded shadow-sm hover:scale-105 group hover:shadow-xl overflow-hidden" href="#" aria-label="View item" title="View item">

    <div class="absolute bottom-0 left-0 w-full h-1 duration-300 origin-left transform scale-x-0 bg-indigo-600 group-hover:scale-x-100"></div>
    <div class="absolute bottom-0 left-0 w-1 h-full duration-300 origin-bottom transform scale-y-0 bg-indigo-600 group-hover:scale-y-100"></div>
    <div class="absolute top-0 left-0 w-full h-1 duration-300 origin-right transform scale-x-0 bg-indigo-600 group-hover:scale-x-100"></div>
    <div class="absolute bottom-0 right-0 w-1 h-full duration-300 origin-top transform scale-y-0 bg-indigo-600 group-hover:scale-y-100"></div>
    <div class="relative flex items-center justify-between p-5 bg-white rounded-sm">

    <img
          src={callout.imageSrc}
          alt={callout.imageAlt}
          className="object-center border border-black  "
        />
    </div>
</a>
</div>
